# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "mailbuilder-preview"
  s.version = "0.1.7"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Darwin"]
  s.date = "2013-10-29"
  s.description = "A nice helper when setting the styling for an email."
  s.email = "darwin.git@marianna.se"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.markdown"
  ]
  s.files = [
    "Gemfile",
    "LICENSE.txt",
    "README.markdown",
    "Rakefile",
    "app/assets/images/mailbuilder-preview/.gitkeep",
    "app/assets/images/mailbuilder-preview/glyphicons-halflings-white.png",
    "app/assets/images/mailbuilder-preview/glyphicons-halflings.png",
    "app/assets/javascripts/mailbuilder-preview/application.js",
    "app/assets/javascripts/mailbuilder-preview/bootstrap.js",
    "app/assets/javascripts/mailbuilder_preview/mail_preview.js",
    "app/assets/stylesheets/mailbuilder-preview/application.css",
    "app/assets/stylesheets/mailbuilder-preview/bootstrap.css",
    "app/assets/stylesheets/mailbuilder_preview/mail_preview.css",
    "app/controllers/mailbuilder_preview/application_controller.rb",
    "app/controllers/mailbuilder_preview/mail_preview_controller.rb",
    "app/helpers/mailbuilder_preview/application_helper.rb",
    "app/views/layouts/mailbuilder_preview/application.html.erb",
    "app/views/mailbuilder_preview/mail_preview/index.html.erb",
    "app/views/mailbuilder_preview/mail_preview/show.html.erb",
    "config/routes.rb",
    "docs/list.png",
    "docs/preview.png",
    "lib/mailbuilder-preview.rb",
    "lib/mailbuilder-preview/engine.rb",
    "lib/mailbuilder-preview/version.rb",
    "lib/tasks/mailbuilder-preview_tasks.rake",
    "mailbuilder-preview.gemspec"
  ]
  s.homepage = "http://github.com/bjornblomqvist/mailbuilder-preview/"
  s.licenses = ["LGPL3"]
  s.require_paths = ["lib"]
  s.rubygems_version = "2.0.6"
  s.summary = "A nice helper when setting the styling for an email."

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<mailbuilder>, [">= 0"])
      s.add_development_dependency(%q<bundler>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 1.8.8"])
    else
      s.add_dependency(%q<mailbuilder>, [">= 0"])
      s.add_dependency(%q<bundler>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 1.8.8"])
    end
  else
    s.add_dependency(%q<mailbuilder>, [">= 0"])
    s.add_dependency(%q<bundler>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 1.8.8"])
  end
end

